
project_id = "zuajpsrnynudfgmqiqch"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
port = 54323

[[edge_functions]]
name = "send-confirmation"
verify_jwt = false

[[edge_functions]]
name = "store-lead"
verify_jwt = false
